Add id to table rows by using table id and row id
meitar/inline-gdocs-viewer pull request #23
Opened 2018-01-27 18:40 UTC by ThaiWood

This allows linking directly to table rows, please let me know if further changes are wanted.

2018-01-28 01:16 UTC, fabacab requested changes
Hey, this looks great, thank you for the patch. Please have a look at line 595 and let me know if you can adjust it as requested.

2018-01-28 01:16 UTC, meitar commented on inline-gdocs-viewer.php
> +        $html  = '<table id="$id"';
Unless I am misreading this, this hunk looks equivalent to the original. Why the change? If the functional execution of this hunk is the same as the original, please leave the original in place and remove this hunk from the commit. Thanks.

2018-02-01 14:45 UTC, ThaiWood commented
@meitar I've reverted that section, please take another look

2018-02-01 22:46 UTC, meitar commented
@ThaiWood Thanks for the update. Lastly, please clean this branch. Something like this should do it, I think:

```sh
git checkout -b pr-23 meitar/master # Make a new branch based on meitar's "master" branch
git merge --squash add-row-id       # Prepare a squashed commit of all the commits in the local `add-row-id` branch.
git commit -m "Add id to table rows by using table id and row id" # Commit that change set.
git push origin +pr-23:add-row-id   # Forcibly overwrite the remote's ("origin") "add-row-id" branch with the contents of the new "pr-23" branch.
```

2018-02-05 22:43 UTC, ThaiWood commented
@meitar, squashed and overwritten as requested

2018-02-06 15:28 UTC, ThaiWood commented
Fixed a typo in 616 where the quotes didn't match, and resquashed

2018-02-06 21:47 UTC, meitar commented
This was merged but the `git svn` command rewrote the commit for compatibility with WordPress.org's Subversion server as 91f51928fd7658b3e8721604f5e6f4ae6b22863b. [Thanks and props](https://github.com/meitar/inline-gdocs-viewer/commit/4600aa71dc58121beb4590aec123d4840141b91a#diff-eb6b6c90251ab33cee784713c451e6d8R289) to your @ThaiWood user account on WordPress.org were provided in the change log and the upgrade notice. :) Many thanks for your contribution, Thai.

2018-02-06 21:47 UTC, closed without merging